#Put your phone number that will get verified by the server here
tel: "+1771111001"

#Server URL
server: https://textsecure-service.whispersystems.org:443

#proxy URL if you use one
#proxy: http://host:8080

#Verification via sms or voice
verificationType: sms

#The local storage uses password base encryption
#If not present here, the password will be requested on startup
storagePassword: password
